version: '3'

services:
  cipherlab:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/app/assets
      - ./templates:/app/templates
    environment:
      - NODE_ENV=development
